
app:
  host: "0.0.0.0"
  grpc_port: "50051"
  grpc_protocol: "tcp"
  http_port: "8080"
database:
  connection: postgres
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: grpc_login
jwt:
  secret: "secret"